name: Tests and Linters 🧪

on: [push, pull_request]

jobs:
  tests-and-linters:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.9"]
        os: [self-hosted]

    steps:
      - name: Install dependencies for viewer test
        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Checkout your repo 📦
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install python dependencies 🔧
        run: pip install -r requirements.txt
      - name: Run linters 🖌️
        run: pre-commit run --all-files --verbose
      # - name: Run tests 🧪
      #   run: pytest --verbose tests
#        run: pytest -n 2 --cov=jumanji --cov-report=term-missing --junit-xml=test-results.xml -vv jumanji
#      - name: Run coverage
#        run: |
#          coverage html --directory=coverage_html_report
#          coverage report --fail-under=0.97
#      - name: Test build docs 📖
#        run: mkdocs build --verbose --site-dir docs_public
